version: '3.3'

services:
  chargebackend:
    build:
      context: ./charge_service_project
    container_name: experimentaldjango
    command: gunicorn experimental_system.wsgi --bind 0.0.0.0:8000
    ports: 
      - 8000:8000
    volumes:
      - ./logs:/app/logs
    restart: always
  
  pcposdjango:
    build:
      context: ./pcposdjango/pcpos_project
    container_name: pcposdjango
    command: gunicorn pcpos.wsgi --bind 0.0.0.0:8001 -w 8 -t 120
    ports: 
      - 8001:8001
    volumes:
      - ./logs:/app/logs
    restart: always
  

  nginx:
    # image: nginx:1.23.4 #latest
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 8080:8080
    volumes:
      # - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/react 
    depends_on:
      - experimentaldjango
      - pcposdjango
    restart: always



