version: '3.3'

services:
  chargebackend:
    build:
      context: ./charge_server/
    container_name: chargebackend
    command: gunicorn charge_service_project.wsgi --bind 0.0.0.0:8000
    ports: 
      - 8000:8000
   
    restart: always
  


