version: '3.3'

services:
  chargebackend:
    build:
      context: ./charge_server/chargedjango
    container_name: chargebackend
    command: gunicorn charge_service_project.wsgi --bind 139.199.214.157:8000
    ports: 
      - 8000:8000
   
    restart: always
  


