# Generated by Django 5.1.7 on 2025-03-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlList',
            fields=[
                ('ACL_id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('station_id', models.CharField(max_length=36)),
                ('driver_token', models.CharField(max_length=80)),
            ],
        ),
    ]
